Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network :forwarded_port, guest: 80, host: 803
  config.vm.network :forwarded_port, guest: 3306, host: 33063
  config.vm.network :forwarded_port, guest: 5432, host: 54333

  # define an ip
  config.vm.network :private_network, ip: "192.168.56.103"

  # create folders
  config.vm.synced_folder "../data", "/var/data", create: true
  config.vm.synced_folder "../misc_data", "/var/misc_data", create: true

  config.vm.provision :shell, :path => "install.sh"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
  end

end
